#include "ui_text.h"

const ui_text_entry_t g_ui_text_en[] = {
    {" started", " started"},
    {"A: enter  B: back", "A: enter  B: back"},
    {"Actions", "Actions"},
    {"Analyze cart", "Analyze cart"},
    {"Analyze first", "Analyze first"},
    {"Average", "Average"},
    {"Battery", "Battery"},
    {"Brightness +", "Brightness +"},
    {"Brightness -", "Brightness -"},
    {"Browse TF", "Browse TF"},
    {"Burn", "Burn"},
    {"Burn direct", "Burn direct"},
    {"Burn pipeline", "Burn pipeline"},
    {"Burn via PSRAM", "Burn via PSRAM"},
    {"Burner", "Burner"},
    {"Bytes", "Bytes"},
    {"Capacity", "Capacity"},
    {"Capacity:", "Capacity:"},
    {"Cart", "Cart"},
    {"Cart info", "Cart info"},
    {"Charging", "Charging"},
    {"Choose TF save", "Choose TF save"},
    {"Clear saved", "Clear saved"},
    {"Connect saved", "Connect saved"},
    {"Count", "Count"},
    {"Count:", "Count:"},
    {"Current", "Current"},
    {"Custom", "Custom"},
    {"Custom MiB", "Custom MiB"},
    {"D1/D0:", "D1/D0:"},
    {"Delete/Rename", "Delete/Rename"},
    {"Device", "Device"},
    {"Disable USB", "Disable USB"},
    {"Disconnect", "Disconnect"},
    {"Dump chunk", "Dump chunk"},
    {"Dump save", "Dump save"},
    {"ESP owns TF", "ESP owns TF"},
    {"Elapsed", "Elapsed"},
    {"Enable USB", "Enable USB"},
    {"Erase", "Erase"},
    {"FRAM", "FRAM"},
    {"FRAM latency", "FRAM latency"},
    {"File", "File"},
    {"File:", "File:"},
    {"Files", "Files"},
    {"Flash1M Repro SRAM patched", "Flash1M Repro SRAM patched"},
    {"Firmware OTA", "Firmware OTA"},
    {"Forget profile", "Forget profile"},
    {"GBA save path does not use FRAM latency", "GBA save path does not use FRAM latency"},
    {"GBC voltage: 3V3", "GBC voltage: 3V3"},
    {"GBC voltage: 5V", "GBC voltage: 5V"},
    {"Game Boy Advance", "Game Boy Advance"},
    {"Game Boy Color", "Game Boy Color"},
    {"Heap", "Heap"},
    {"Language", "Language"},
    {"Locked", "Locked"},
    {"MBC5 only", "MBC5 only"},
    {"Mapping", "Mapping"},
    {"MiB", "MiB"},
    {"NOR geom", "NOR geom"},
    {"New folder", "New folder"},
    {"No", "No"},
    {"Not patched", "Not patched"},
    {"Not scanned", "Not scanned"},
    {"No probe detail", "No probe detail"},
    {"OK", "OK"},
    {"Only Analyze cart is available", "Only Analyze cart is available"},
    {"Patched", "Patched"},
    {"PC owns TF", "PC owns TF"},
    {"PPB already unlocked", "PPB already unlocked"},
    {"PPB unlock failed", "PPB unlock failed"},
    {"PPB unlocked", "PPB unlocked"},
    {"PPB unlocking", "PPB unlocking"},
    {"PSRAM window", "PSRAM window"},
    {"PSRAM window changed", "PSRAM window changed"},
    {"PSRAM/chunk/voltage", "PSRAM/chunk/voltage"},
    {"PSRAM/dump chunk", "PSRAM/dump chunk"},
    {"Path", "Path"},
    {"Power", "Power"},
    {"Progress", "Progress"},
    {"Provision AP", "Provision AP"},
    {"RAM operations", "RAM operations"},
    {"RAM size", "RAM size"},
    {"RAM type", "RAM type"},
    {"RAM: Choose save", "RAM: Choose save"},
    {"RAM: Dump", "RAM: Dump"},
    {"RAM: Operations", "RAM: Operations"},
    {"RAM: Verify", "RAM: Verify"},
    {"RAM: Write", "RAM: Write"},
    {"ROM dump started", "ROM dump started"},
    {"ROM selected", "ROM selected"},
    {"ROM/File", "ROM/File"},
    {"ROM: Choose file", "ROM: Choose file"},
    {"ROM: Dump", "ROM: Dump"},
    {"ROM: Erase chip", "ROM: Erase chip"},
    {"ROM: Reselect file", "ROM: Reselect file"},
    {"ROM: Unlock PPB", "ROM: Unlock PPB"},
    {"ROM: Verify", "ROM: Verify"},
    {"ROM: Write", "ROM: Write"},
    {"Re-analyze", "Re-analyze"},
    {"Refresh", "Refresh"},
    {"Restart", "Restart"},
    {"SRAM", "SRAM"},
    {"SRAM patch", "SRAM patch"},
    {"SRAM patch:", "SRAM patch:"},
    {"STA profile", "STA profile"},
    {"Save", "Save"},
    {"Save file", "Save file"},
    {"Save size", "Save size"},
    {"Save:", "Save:"},
    {"Sector", "Sector"},
    {"Sector:", "Sector:"},
    {"Select cart type", "Select cart type"},
    {"Select file first!!!", "Select file first!!!"},
    {"Settings", "Settings"},
    {"Setup portal", "Setup portal"},
    {"Size", "Size"},
    {"Size:", "Size:"},
    {"Slot", "Slot"},
    {"Speed", "Speed"},
    {"State", "State"},
    {"Stop STA", "Stop STA"},
    {"Storage", "Storage"},
    {"System", "System"},
    {"TF busy by USB host", "TF busy by USB host"},
    {"TF card not ready", "TF card not ready"},
    {"TF manager", "TF manager"},
    {"TF not available", "TF not available"},
    {"TF root", "TF root"},
    {"Task", "Task"},
    {"Task status", "Task status"},
    {"Then operations unlock", "Then operations unlock"},
    {"Type", "Type"},
    {"Type:", "Type:"},
    {"USB owns TF", "USB owns TF"},
    {"USB pass-through disabled", "USB pass-through disabled"},
    {"USB pass-through enabled", "USB pass-through enabled"},
    {"Upload files", "Upload files"},
    {"Uptime", "Uptime"},
    {"Verify GBA save", "Verify GBA save"},
    {"Verify ROM", "Verify ROM"},
    {"Verify save", "Verify save"},
    {"Version", "Version"},
    {"Voltage", "Voltage"},
    {"Voltage settle", "Voltage settle"},
    {"Voltage settle changed", "Voltage settle changed"},
    {"Web deploy", "Web deploy"},
    {"GBATA SRAM patched", "GBATA SRAM patched"},
    {"Wi-Fi connected", "Wi-Fi connected"},
    {"Wi-Fi connected %s", "Wi-Fi connected %s"},
    {"Wi-Fi disconnected", "Wi-Fi disconnected"},
    {"Wi-Fi working", "Wi-Fi working"},
    {"Write GBA save", "Write GBA save"},
    {"Write save", "Write save"},
    {"Yes, erase chip", "Yes, erase chip"},
    {"Yes, stop task", "Yes, stop task"},
    {"action already running", "action already running"},
    {"action failed: ", "action failed: "},
    {"analyze cart first", "analyze cart first"},
    {"analyze first", "analyze first"},
    {"analyzed", "analyzed"},
    {"battery telemetry", "battery telemetry"},
    {"brightness down", "brightness down"},
    {"brightness up", "brightness up"},
    {"burn progress", "burn progress"},
    {"cancel", "cancel"},
    {"cancelled", "cancelled"},
    {"cancelling task", "cancelling task"},
    {"card missing", "card missing"},
    {"cart analyzed", "cart analyzed"},
    {"cart operations", "cart operations"},
    {"chip erase cancelled", "chip erase cancelled"},
    {"chip erase started", "chip erase started"},
    {"choose method", "choose method"},
    {"clear sector protection", "clear sector protection"},
    {"confirm chip erase", "confirm chip erase"},
    {"confirm stop task", "confirm stop task"},
    {"connected", "connected"},
    {"connecting Wi-Fi", "connecting Wi-Fi"},
    {"continue current task", "continue current task"},
    {"current language", "English"},
    {"danger", "danger"},
    {"device tools", "device tools"},
    {"dir", "dir"},
    {"directory clipped", "directory clipped"},
    {"disconnected", "disconnected"},
    {"done", "done"},
    {"dump ROM", "dump ROM"},
    {"dump chunk changed", "dump chunk changed"},
    {"empty directory", "empty directory"},
    {"error", "error"},
    {"file details", "file details"},
    {"file type mismatch", "file type mismatch"},
    {"files and USB", "files and USB"},
    {"free prefix", "free"},
    {"free suffix", "free"},
    {"idle", "idle"},
    {"info panel left", "info panel left"},
    {"info panel right", "info panel right"},
    {"initializing", "initializing"},
    {"input MiB size", "input MiB size"},
    {"input size first", "input size first"},
    {"invalid path", "invalid path"},
    {"keypad", "keypad"},
    {"latency changed", "latency changed"},
    {"missing", "missing"},
    {"network setup", "network setup"},
    {"no", "no"},
    {"no file selected", "no file selected"},
    {"no matching files", "no matching files"},
    {"no memory", "no memory"},
    {"normal", "normal"},
    {"not probed", "not probed"},
    {"not selected", "not selected"},
    {"open directory failed", "open directory failed"},
    {"open files", "open files"},
    {"path too long", "path too long"},
    {"provisioning", "provisioning"},
    {"provisioning AP", "provisioning AP"},
    {"read id failed", "read id failed"},
    {"read only", "read only"},
    {"ready", "ready"},
    {"reboot device", "reboot device"},
    {"receiving", "receiving"},
    {"refreshed", "refreshed"},
    {"restarting", "restarting"},
    {"running", "running"},
    {"save dump started", "save dump started"},
    {"save selected", "save selected"},
    {"save size changed", "save size changed"},
    {"save write/dump", "save write/dump"},
    {"saved Wi-Fi cleared", "saved Wi-Fi cleared"},
    {"select TF ROM first", "select TF ROM first"},
    {"select TF save first", "select TF save first"},
    {"select dump size", "select dump size"},
    {"select size", "select size"},
    {"select write method", "select write method"},
    {"selected file is not ROM", "selected file is not ROM"},
    {"selected file is not save", "selected file is not save"},
    {"slot changed", "slot changed"},
    {"start failed: ", "start failed: "},
    {"starting burn task", "starting burn task"},
    {"storage working", "storage working"},
    {"swapped", "swapped"},
    {"system overview", "system overview"},
    {"task starting", "task starting"},
    {"task status", "task status"},
    {"return to previous page", "return to previous page"},
    {"telemetry", "telemetry"},
    {"unknown", "unknown"},
    {"unsupported file", "unsupported file"},
    {"use web page for this TF action", "use web page for this TF action"},
    {"use web page for this setting", "use web page for this setting"},
    {"web action", "web action"},
    {"web overview", "web overview"},
    {"working", "working"},
    {"yes", "yes"},
};

const size_t g_ui_text_en_count = sizeof(g_ui_text_en) / sizeof(g_ui_text_en[0]);
