#include "ui_text.h"

const ui_text_entry_t g_ui_text_zh[] = {
    {" started", "已启动"},
    {"A: enter  B: back", "A进入 B返回"},
    {"Actions", "操作"},
    {"Analyze cart", "分析卡带"},
    {"Analyze first", "请先分析卡带"},
    {"Average", "平均"},
    {"Battery", "电池"},
    {"Brightness +", "亮度+"},
    {"Brightness -", "亮度-"},
    {"Browse TF", "浏览TF卡"},
    {"Burn", "烧录"},
    {"Burn direct", "直接烧录"},
    {"Burn pipeline", "流水线烧录"},
    {"Burn via PSRAM", "PSRAM烧录"},
    {"Burner", "烧录器"},
    {"Bytes", "字节"},
    {"Capacity", "容量"},
    {"Capacity:", "容量:"},
    {"Cart", "卡带"},
    {"Cart info", "卡带信息"},
    {"Charging", "充电"},
    {"Choose TF save", "选择TF存档"},
    {"Clear saved", "清除配置"},
    {"Connect saved", "连接已保存"},
    {"Count", "扇区数"},
    {"Count:", "扇区数:"},
    {"Current", "当前状态"},
    {"Custom", "自定义"},
    {"Custom MiB", "自定义MiB"},
    {"D1/D0:", "D1/D0:"},
    {"Delete/Rename", "删除/重命名"},
    {"Device", "设备"},
    {"Disable USB", "禁用USB"},
    {"Disconnect", "断开连接"},
    {"Dump chunk", "读取块"},
    {"Dump read avg", "读卡平均"},
    {"Dump read max", "读卡最高"},
    {"Dump save", "读取存档"},
    {"Dump write avg", "写TF平均"},
    {"Dump write max", "写TF最高"},
    {"ESP owns TF", "ESP访问TF"},
    {"Elapsed", "耗时"},
    {"Enable USB", "启用USB"},
    {"Erase", "擦除"},
    {"Erase time", "擦除耗时"},
    {"FRAM", "FRAM"},
    {"FRAM latency", "FRAM延迟"},
    {"File", "文件"},
    {"File:", "文件:"},
    {"Files", "文件"},
    {"Flash1M Repro SRAM patched", "已打Flash1M Repro的SRAM补丁"},
    {"Firmware OTA", "固件OTA"},
    {"Forget profile", "忘记Wi-Fi"},
    {"GBA save path does not use FRAM latency", "GBA存档流程不使用FRAM延迟"},
    {"GBC voltage: 3V3", "GBC电压: 3V3"},
    {"GBC voltage: 5V", "GBC电压: 5V"},
    {"Game Boy Advance", "GBA卡带"},
    {"Game Boy Color", "GBC卡带"},
    {"Heap", "内存"},
    {"Language", "语言"},
    {"Locked", "未解锁"},
    {"MBC5 only", "仅MBC5"},
    {"Mapping", "映射"},
    {"MiB", "MiB"},
    {"NOR geom", "NOR参数"},
    {"New folder", "新建文件夹"},
    {"No", "否"},
    {"Not patched", "未打补丁"},
    {"No probe detail", "暂无详细参数"},
    {"OK", "确定"},
    {"Only Analyze cart is available", "请先分析卡带，之后解锁操作"},
    {"Patched", "已打补丁"},
    {"PC owns TF", "电脑访问TF"},
    {"PPB already unlocked", "PPB已经解锁"},
    {"PPB unlock failed", "PPB解锁失败"},
    {"PPB unlocked", "PPB已解锁"},
    {"PPB unlocking", "PPB解锁中"},
    {"PSRAM window", "PSRAM窗口"},
    {"PSRAM window changed", "PSRAM窗口已改变"},
    {"PSRAM/chunk/voltage", "PSRAM/读取块/电压"},
    {"PSRAM/dump chunk", "PSRAM/读取块"},
    {"Path", "路径"},
    {"Power", "电源"},
    {"Progress", "进度"},
    {"Provision AP", "开启配网AP"},
    {"RAM operations", "RAM操作"},
    {"RAM size", "RAM大小"},
    {"RAM type", "RAM类型"},
    {"RAM: Choose save", "RAM: 选择存档"},
    {"RAM: Dump", "RAM: 读取"},
    {"RAM: Operations", "RAM: 操作"},
    {"RAM: Verify", "RAM: 校验"},
    {"RAM: Write", "RAM: 写入"},
    {"ROM dump started", "ROM读取已启动"},
    {"ROM selected", "已选择ROM"},
    {"ROM/File", "ROM/文件"},
    {"ROM: Choose MBC", "ROM: 选择MBC"},
    {"ROM: Choose file", "ROM: 选择文件"},
    {"ROM: Dump", "ROM: 读取"},
    {"ROM: Erase chip", "ROM: 整片擦除"},
    {"ROM: Reselect file", "ROM: 重选文件"},
    {"ROM: Unlock PPB", "ROM: 解锁PPB"},
    {"ROM: Verify", "ROM: 校验"},
    {"ROM: Write", "ROM: 写入"},
    {"Re-analyze", "重新分析"},
    {"Refresh", "刷新"},
    {"Restart", "重启"},
    {"Result", "结算"},
    {"SRAM", "SRAM"},
    {"SRAM patch", "SRAM补丁"},
    {"SRAM patch:", "SRAM补丁:"},
    {"STA profile", "STA配置"},
    {"Save", "存档"},
    {"Save file", "存档文件"},
    {"Save size", "存档大小"},
    {"Save:", "存档:"},
    {"Sector", "扇区大小"},
    {"Sector:", "扇区大小:"},
    {"Select cart type", "选择卡带类型"},
    {"Select file first!!!", "先选文件!!!"},
    {"Settings", "设置"},
    {"Setup portal", "设置入口"},
    {"Size", "大小"},
    {"Size:", "大小:"},
    {"Slot", "槽位"},
    {"Speed", "速度"},
    {"State", "状态"},
    {"Stop STA", "停止STA"},
    {"Storage", "存储"},
    {"System", "系统"},
    {"TF busy by USB host", "TF被USB占用"},
    {"TF card not ready", "TF卡未就绪"},
    {"TF manager", "TF管理"},
    {"TF not available", "TF不可用"},
    {"TF root", "TF根目录"},
    {"TF->PSRAM avg", "TF到PSRAM平均"},
    {"TF->PSRAM max", "TF到PSRAM最高"},
    {"Task", "任务"},
    {"Task status", "任务状态"},
    {"Then operations unlock", "之后会解锁操作"},
    {"Total time", "总耗时"},
    {"Type", "类型"},
    {"Type:", "类型:"},
    {"USB owns TF", "USB占用TF"},
    {"USB pass-through disabled", "USB直通已禁用"},
    {"USB pass-through enabled", "USB直通已启用"},
    {"Upload files", "上传文件"},
    {"Uptime", "运行时间"},
    {"Verify GBA save", "校验GBA存档"},
    {"Verify ROM", "校验ROM"},
    {"Verify save", "校验存档"},
    {"Version", "版本"},
    {"Voltage", "电压"},
    {"Voltage settle", "切压延时"},
    {"Voltage settle changed", "切压延时已改变"},
    {"Web deploy", "网页部署"},
    {"GBATA SRAM patched", "已打GBATA的SRAM补丁"},
    {"Wi-Fi connected", "Wi-Fi已连接"},
    {"Wi-Fi connected %s", "Wi-Fi已连接 %s"},
    {"Wi-Fi disconnected", "Wi-Fi已断开"},
    {"Wi-Fi working", "Wi-Fi处理中"},
    {"Write GBA save", "写入GBA存档"},
    {"Write avg", "写入平均"},
    {"Write max", "写入最高"},
    {"Write min", "写入最低"},
    {"Write save", "写入存档"},
    {"Write time", "写入耗时"},
    {"Yes, erase chip", "是，整片擦除"},
    {"Yes, stop task", "是，终止任务"},
    {"action already running", "操作正在运行"},
    {"action failed: ", "操作失败: "},
    {"analyze cart first", "请先分析卡带"},
    {"analyze first", "请先分析"},
    {"analyzed", "已分析"},
    {"battery telemetry", "电源状态"},
    {"brightness down", "亮度已降低"},
    {"brightness up", "亮度已增加"},
    {"burn progress", "烧录进度"},
    {"cancel", "取消"},
    {"cancelled", "已取消"},
    {"cancelling task", "正在中止任务"},
    {"card missing", "未插卡"},
    {"cart analyzed", "卡带已分析"},
    {"cart operations", "卡带操作"},
    {"chip erase cancelled", "已取消整片擦除"},
    {"chip erase started", "整片擦除已启动"},
    {"choose method", "选择方式"},
    {"clear sector protection", "清除扇区保护"},
    {"confirm chip erase", "请确认整片擦除"},
    {"confirm stop task", "确认中止当前任务"},
    {"connected", "已连接"},
    {"connecting Wi-Fi", "正在连接Wi-Fi"},
    {"continue current task", "继续当前任务"},
    {"current language", "中文"},
    {"danger", "危险操作"},
    {"device tools", "设备工具"},
    {"dir", "目录"},
    {"directory clipped", "目录已截断"},
    {"disconnected", "未连接"},
    {"done", "完成"},
    {"dump ROM", "读取ROM"},
    {"dump chunk changed", "读取块已改变"},
    {"empty directory", "空目录"},
    {"error", "错误"},
    {"file details", "文件详情"},
    {"file type mismatch", "文件类型不匹配"},
    {"files and USB", "文件与USB"},
    {"free prefix", "剩余"},
    {"free suffix", "free"},
    {"idle", "空闲"},
    {"info panel left", "信息面板在左"},
    {"info panel right", "信息面板在右"},
    {"initializing", "初始化中"},
    {"input MiB size", "输入MiB大小"},
    {"input size first", "请先输入大小"},
    {"invalid path", "路径无效"},
    {"keypad", "键盘"},
    {"latency changed", "延迟已改变"},
    {"missing", "未插卡"},
    {"network setup", "网络设置"},
    {"no", "否"},
    {"no file selected", "未选择文件"},
    {"no matching files", "没有匹配文件"},
    {"no memory", "内存不足"},
    {"normal", "正常"},
    {"not probed", "未探测"},
    {"not selected", "未选择"},
    {"open directory failed", "打开目录失败"},
    {"open files", "打开文件"},
    {"path too long", "路径过长"},
    {"provisioning", "配网中"},
    {"provisioning AP", "配网热点已开启"},
    {"read id failed", "读取ID失败"},
    {"read only", "只读"},
    {"ready", "就绪"},
    {"reboot device", "重启设备"},
    {"receiving", "接收中"},
    {"refreshed", "已刷新"},
    {"restarting", "正在重启"},
    {"result summary", "结算统计"},
    {"running", "运行中"},
    {"save dump started", "存档读取已启动"},
    {"save selected", "已选择存档"},
    {"save size changed", "存档大小已改变"},
    {"save write/dump", "存档写入/读取"},
    {"saved Wi-Fi cleared", "已清除Wi-Fi"},
    {"select TF ROM first", "请先选择TF ROM"},
    {"select TF save first", "请先选择TF存档"},
    {"select dump size", "请选择读取大小"},
    {"select size", "选择大小"},
    {"select write method", "请选择烧录方式"},
    {"selected file is not ROM", "所选文件不是ROM"},
    {"selected file is not save", "所选文件不是存档"},
    {"slot changed", "槽位已改变"},
    {"start failed: ", "启动失败: "},
    {"starting burn task", "正在启动烧录任务"},
    {"storage working", "存储处理中"},
    {"swapped", "对调"},
    {"system overview", "系统概览"},
    {"task starting", "任务启动中"},
    {"task status", "任务状态"},
    {"return to previous page", "返回上一级"},
    {"telemetry", "状态"},
    {"unknown", "未知"},
    {"unsupported file", "不支持的文件"},
    {"use web page for this TF action", "请在网页操作TF"},
    {"use web page for this setting", "请在网页设置"},
    {"web action", "网页操作"},
    {"web overview", "系统概览"},
    {"working", "处理中"},
    {"yes", "是"},
};

const size_t g_ui_text_zh_count = sizeof(g_ui_text_zh) / sizeof(g_ui_text_zh[0]);
