module bacon (
  inout       [23:16] A,
  inout       [15:0] AD,
  output tri0        CART_DIR_A,
  output tri0        CART_DIR_AD,
  output tri0        CS1_N,
  output tri0        CS2_N,
  input              ESP32_SPI2_CS_N,
  output tri0        ESP32_SPI2_MISO,
  input              ESP32_SPI2_MOSI,
  input              ESP32_SPI_CS1,
  inout              IRQ,
  output tri0        LED_ACT,
  output tri0        LED_READY,
  inout              MCU_SPI_CLK,
  inout              PHI,
  output tri0        RD_N,
  output tri0        V3V3_CTRL,
  output tri0        V5V_CTRL,
  output tri0        WR_N,
  input              sys_clock,
  input              bus_clock,
  input              resetn,
  input              stop,
  input       [1:0]  mem_ahb_htrans,
  input              mem_ahb_hready,
  input              mem_ahb_hwrite,
  input       [31:0] mem_ahb_haddr,
  input       [2:0]  mem_ahb_hsize,
  input       [2:0]  mem_ahb_hburst,
  input       [31:0] mem_ahb_hwdata,
  output tri1        mem_ahb_hreadyout,
  output tri0        mem_ahb_hresp,
  output tri0 [31:0] mem_ahb_hrdata,
  output tri0        slave_ahb_hsel,
  output tri1        slave_ahb_hready,
  input              slave_ahb_hreadyout,
  output tri0 [1:0]  slave_ahb_htrans,
  output tri0 [2:0]  slave_ahb_hsize,
  output tri0 [2:0]  slave_ahb_hburst,
  output tri0        slave_ahb_hwrite,
  output tri0 [31:0] slave_ahb_haddr,
  output tri0 [31:0] slave_ahb_hwdata,
  input              slave_ahb_hresp,
  input       [31:0] slave_ahb_hrdata,
  output tri0 [3:0]  ext_dma_DMACBREQ,
  output tri0 [3:0]  ext_dma_DMACLBREQ,
  output tri0 [3:0]  ext_dma_DMACSREQ,
  output tri0 [3:0]  ext_dma_DMACLSREQ,
  input       [3:0]  ext_dma_DMACCLR,
  input       [3:0]  ext_dma_DMACTC,
  output tri0 [3:0]  local_int
);
assign mem_ahb_hreadyout = 1'b1;
assign slave_ahb_hready  = 1'b1;
endmodule
