#pragma once

/* Included after the burner enums. One definition across all translation units:
 * adding a field must never change only the extern declaration of s_status. */
#define BURNER_PROBE_CHIP_NAME_LEN 48
#define BURNER_PROBE_MAPPER_NAME_LEN 24

typedef struct {
    burner_state_t state;
    int progress;
    uint32_t total_bytes;
    uint32_t processed_bytes;
    uint64_t speed_start_us;
    uint64_t speed_warmup_until_us;
    uint64_t speed_last_us;
    uint32_t speed_start_bytes;
    uint32_t speed_last_bytes;
    uint32_t speed_current_bps;
    uint32_t speed_avg_bps;
    uint32_t speed_min_bps;
    uint32_t speed_max_bps;
    bool write_speed_manual;
    uint64_t task_start_us;
    uint64_t task_elapsed_us;
    uint32_t erase_sector_count;
    uint32_t erase_sector_size;
    uint32_t erase_phase_total_sectors;
    uint32_t erase_phase_done_sectors;
    uint32_t erase_phase_total_bytes;
    uint32_t erase_phase_done_bytes;
    uint64_t erase_start_us;
    uint64_t erase_elapsed_us;
    uint64_t write_start_us;
    /* Accumulated cartridge programming intervals, excluding erase/TF I/O. */
    uint64_t write_elapsed_us;
    uint64_t write_erase_base_us;
    uint32_t tf_to_psram_speed_current_bps;
    uint32_t tf_to_psram_speed_avg_bps;
    uint32_t tf_to_psram_speed_min_bps;
    uint32_t tf_to_psram_speed_max_bps;
    uint32_t dump_read_speed_current_bps;
    uint32_t dump_read_speed_avg_bps;
    uint32_t dump_read_speed_min_bps;
    uint32_t dump_read_speed_max_bps;
    uint32_t dump_write_speed_current_bps;
    uint32_t dump_write_speed_avg_bps;
    uint32_t dump_write_speed_min_bps;
    uint32_t dump_write_speed_max_bps;
    uint32_t mbc5_buffer_write_ok_count;
    uint32_t mbc5_buffer_fallback_count;
    uint32_t write_skipped_bytes;
    uint32_t write_matched_bytes;
    uint32_t write_speed_total_bytes;
    uint64_t write_speed_total_us;
    uint32_t tf_to_psram_total_bytes;
    uint64_t tf_to_psram_total_us;
    uint32_t dump_read_total_bytes;
    uint64_t dump_read_total_us;
    uint32_t dump_write_total_bytes;
    uint64_t dump_write_total_us;
    uint64_t dump_wait_total_us;
    uint64_t dump_finalize_total_us;
    uint32_t verify_sample_addr;
    uint8_t verify_sample_file_byte;
    uint8_t verify_sample_cart_byte;
    bool verify_sample_valid;
    bool verify_sample_equal;
    burner_cart_mode_t probe_cart_mode;
    bool probe_valid;
    bool probe_cfi_ok;
    bool probe_gba_multi;
    bool probe_gba_force_multi;
    bool probe_gba_d0d1_known;
    bool probe_gba_d0d1_swapped;
    burner_gba_save_type_t probe_gba_save_type;
    uint32_t probe_gba_save_size;
    bool probe_gba_save_detected;
    uint32_t probe_gba_batteryless_save_address;
    uint32_t probe_gba_batteryless_save_size;
    bool probe_gba_batteryless_region_found;
    bool probe_gba_batteryless_data_present;
    burner_gba_sram_patch_kind_t probe_gba_sram_patch_kind;
    bool probe_gba_sram_patch_scanned;
    bool probe_gba_sram_patch_detected;
    uint32_t probe_device_size;
    uint32_t probe_sector_size;
    uint16_t probe_buffer_write_bytes;
    uint8_t probe_id[8];
    char probe_chip_name[BURNER_PROBE_CHIP_NAME_LEN];
    char probe_mapper_name[BURNER_PROBE_MAPPER_NAME_LEN];
    char rom_name[BURNER_FILE_NAME_LEN];
    char rom_path[BURNER_FILE_PATH_LEN];
    char message[96];
    bool chip_erase_ui_active;
    bool erase_phase_planned;
    bool erase_phase_active;
    bool cancel_requested;
} burner_status_t;
